--SELECT DISTINCT replacement_cost from film
--SELECT count(DISTINCT replacement_cost) from film
--select count(title) from film where title like 'T%' and rating='G'
--select count(*) from country where country like '_____'
--select count(*) from city where city ilike '%r'