--select country,city from country inner join city on country.country_id=city.country_id order by 1
--select payment_id,first_name,last_name from customer join payment  on payment.customer_id=customer.customer_id
--select rental_id,first_name,last_name from rental join customer on customer.customer_id=rental.customer_id